// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtWjGwsjtlfb5BEUxkC4YcyaCbiXgSgAo',
    appId: '1:994980821640:web:48f7caa873a10dea5cfd3d',
    messagingSenderId: '994980821640',
    projectId: 'walk-app-2026',
    authDomain: 'walk-app-2026.firebaseapp.com',
    storageBucket: 'walk-app-2026.firebasestorage.app',
    measurementId: 'G-70J0MFELDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvgW2CTzU8hO30OvSaaihjuVDjNyGN4QQ',
    appId: '1:994980821640:android:c3f0e6ce45b508755cfd3d',
    messagingSenderId: '994980821640',
    projectId: 'walk-app-2026',
    storageBucket: 'walk-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEPWLDzLYEA57fGvDEosHv4jxqxIBSSmc',
    appId: '1:994980821640:ios:523f524292c263ee5cfd3d',
    messagingSenderId: '994980821640',
    projectId: 'walk-app-2026',
    storageBucket: 'walk-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEPWLDzLYEA57fGvDEosHv4jxqxIBSSmc',
    appId: '1:994980821640:ios:523f524292c263ee5cfd3d',
    messagingSenderId: '994980821640',
    projectId: 'walk-app-2026',
    storageBucket: 'walk-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtWjGwsjtlfb5BEUxkC4YcyaCbiXgSgAo',
    appId: '1:994980821640:web:bac53f63c3dee9da5cfd3d',
    messagingSenderId: '994980821640',
    projectId: 'walk-app-2026',
    authDomain: 'walk-app-2026.firebaseapp.com',
    storageBucket: 'walk-app-2026.firebasestorage.app',
    measurementId: 'G-4V9QWJPYG4',
  );
}
